run:
	gcc -o milk milk.c -lpthread && ./milk
	gcc -o phy phy.c -lpthread && ./phy
milk:
	gcc -o milk milk.c -lpthread && ./milk
phy:
	gcc -o phy1 phy1.c -lpthread && ./phy1
	gcc -o phy2 phy2.c -lpthread && ./phy2
clean:
	rm milk phy