# Automatically generated by configure - do not modify
SRC_PATH=/home/lrj11911808/2022_os/lab/lab01/qemu-5.0.0/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
